name: Common CI Setup
description: Checkout + Java + optional Xcode + optional KVM

inputs:
  override-cache:
    description: 'Override Cache?'
    required: false
    default: "false"
  enable-kvm:
    description: Enable KVM for Android emulator tests
    required: false
    default: "false" # composite inputs are strings
  setup-xcode:
    description: "Setup XCode version"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: "17"

    - name: Setup Xcode
      if: ${{ runner.os == 'macOS' &&  inputs.setup-xcode == 'true' }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "26.4"

    - name: Enable KVM
      if: ${{ inputs.enable-kvm == 'true' }}
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Setup Gradle # Gradle-native cache handling
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-read-only: ${{ inputs.override-cache != 'true' }}
        cache-cleanup: 'never'
        dependency-graph: ${{ inputs.override-cache == 'true' && 'generate-and-submit' || 'disabled' }} # Dependency graph for Dependabot
